/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MgGreetings {
    }
}
declare global {
    interface HTMLMgGreetingsElement extends Components.MgGreetings, HTMLStencilElement {
    }
    var HTMLMgGreetingsElement: {
        prototype: HTMLMgGreetingsElement;
        new (): HTMLMgGreetingsElement;
    };
    interface HTMLElementTagNameMap {
        "mg-greetings": HTMLMgGreetingsElement;
    }
}
declare namespace LocalJSX {
    interface MgGreetings {
    }
    interface IntrinsicElements {
        "mg-greetings": MgGreetings;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mg-greetings": LocalJSX.MgGreetings & JSXBase.HTMLAttributes<HTMLMgGreetingsElement>;
        }
    }
}
